Dodanie uwag do API
marcin2x/DistributedMonitor pull request #11
Opened 2017-03-25 17:05 UTC by marcin2x

2017-04-01 11:45 UTC, Trillon commented on docs/REST_API-Draft/issues.md
> +1.  Pobranie listy monitorów dla danego użytkownika:
Zrobione

2017-04-01 12:02 UTC, Trillon requested changes
Wprowadziłem poprawki z dokumentu i od prowadzacego

2017-04-01 12:02 UTC, Trillon commented on docs/REST_API-Draft/issues.md
> +1. Użytkownik może dodać monitor
Zrobione

2017-04-01 12:02 UTC, Trillon commented on docs/REST_API-Draft/issues.md
> +1. Użytkownik może usunąć monitor
Zrobione

2017-04-01 12:02 UTC, Trillon commented on docs/REST_API-Draft/issues.md
> +### Komunikcja Sensor -> Monitor
Zgodnie z komentarzem prowadzącego to będzie realizowane inaczej(takiego maila dostałem od @kassqaa )

2017-04-01 12:02 UTC, Trillon commented on docs/REST_API-Draft/issues.md
> +1. "Pobranie pomiarów"
Zrobione

2017-04-01 12:02 UTC, Trillon commented on docs/REST_API-Draft/issues.md
> +1. "Pobranie wartości pomiarów"
Zrobione

2017-04-01 12:02 UTC, Trillon commented on docs/REST_API-Draft/issues.md
> +1. "Pobranie sensorow"
To zostało usunietę, w związku z uwagą prowadzącego

2017-04-01 12:02 UTC, Trillon commented on docs/REST_API-Draft/issues.md
> +1. "Utworzenie nowego pomiaru złożonego"
Zrobione

2017-04-01 12:02 UTC, Trillon commented on docs/REST_API-Draft/issues.md
> +1. "Pobranie wartości pomiarów złożonych"
Tutaj dodałem opcjonalne pole do pobierania pomiarów, służace do pobierania tylko wartosci pomiarów złożonych

2017-04-01 12:02 UTC, Trillon commented on docs/REST_API-Draft/issues.md
> +1. "Pobranie pomiarów złożonych"
Zrobione

2017-04-02 09:23 UTC, marcin2x commented on docs/REST_API-Draft/draft.md
> +GET /measurements/{id}/values
chyba nie mamy tego id nigdzie teraz.. trzeba to będzie przemyśleć

2017-04-26 15:58 UTC, marcin2x commented on docs/REST_API-Draft/draft.md
>      measurement_id: [long]
powinno być monitor_id

2017-04-26 15:59 UTC, marcin2x commented on docs/REST_API-Draft/draft.md
> +    monitor : [object]
można opisać obiekt monitora - że ma zawierać: name, port, adres

2017-04-26 15:59 UTC, marcin2x commented on docs/REST_API-Draft/draft.md
> +            adres : [string]
address

2017-04-26 16:01 UTC, marcin2x commented on docs/REST_API-Draft/draft.md
> +			interval : [long],
w jakiej jednostce jest interval?

2017-04-26 16:01 UTC, marcin2x commented on docs/REST_API-Draft/draft.md
>  | measurment_name | wymagany | nazwa pomiaru |  |
literówka w "measurment_name "

2017-04-26 16:03 UTC, marcin2x commented on docs/REST_API-Draft/draft.md
>  | measurment_name | wymagany | nazwa pomiaru |  |
pasuje też uwspólnić nazwy, bo raz mamy myślnik (host-name), a raz podkreślenie (measurment_name)

2017-04-26 16:04 UTC, marcin2x commented on docs/REST_API-Draft/draft.md
> +            date: [string]
Można określić format daty jakiego używamy, bo JSON nie określa jednego konkretnego

2017-04-26 16:05 UTC, marcin2x commented on docs/REST_API-Draft/draft.md
> +			value: [string],
a value chyba powinno być liczbą całkowitą

2017-04-26 16:06 UTC, marcin2x commented on docs/REST_API-Draft/draft.md
>  | measurement-names | opcjonalny | nazwa poszukiwanych pomiarów | |
chyba wystarczy liczba pojedyncza (measurement-name) (tak samo w host-names), bo użytkownik i tak w GUI nie poda raczej kilku (nie ma na to wymagania)

2017-04-26 16:07 UTC, marcin2x commented on docs/REST_API-Draft/draft.md
>  | measurment_name | wymagany | nazwa pomiaru |  |
i z tego co mówiliśmy, to mieliśmy zamienić na measurment_id (tak pamiętam ze spotkania)

2017-04-26 16:09 UTC, marcin2x commented on docs/REST_API-Draft/draft.md
> +| names | opcjonalny | nazwa poszukiwanych hostów | |
tutaj znowu wystarczy liczba pojedynzca (przy name)

2017-04-26 16:13 UTC, marcin2x commented on docs/REST_API-Draft/draft.md
> +| name | wymagany | nazwa hosta |  |
powinniśmy też zwracać metadane hosta i jego pomiary np:
```
measurements: [{id:1, description: "RAM"}, ...],
metadata: [{key:"Core number", value: "3"}, ...]
```

2017-04-26 16:14 UTC, marcin2x commented on docs/REST_API-Draft/draft.md
>  ### Wylogowanie
Rozbij to jak możesz na 2 pliki (Autoryzacja i Operacje na danych oddzielnie).
Dodatkowo brakuje opisu modeli do komunikacji po TCP/IP Sensor -> Monitor

2017-04-27 16:43 UTC, marcin2x commented on docs/REST_API-Draft/data_opertations.md
> +## Monitory
Pobieranie monitorów będzie częścią serwisu autentykującego, wiec można przerzucić do pliku auth.md

2017-04-27 16:44 UTC, marcin2x commented on docs/REST_API-Draft/auth.md
> +# Autoryzacja
brakuje rejestracji

2017-04-27 16:44 UTC, marcin2x commented on docs/REST_API-Draft/data_opertations.md
> +## Monitory
Tak samo tworzenie monitora

2017-04-28 22:12 UTC, merged